AWSTemplateFormatVersion: "2010-09-09"
Description: VPC and Subnet Create


Parameters:
 NameBase: 
  Description: this is base name
  Type: String
  Default: raisetech2


Resources:
 # vpc
 VPC:
   Type: AWS::EC2::VPC
   Properties:
    CidrBlock: 10.1.0.0/16
    EnableDnsSupport: true
    EnableDnsHostnames: true
    Tags:
     - Key: Name
       Value: !Sub ${NameBase}-vpc


 # subnet
 PublicSubnet1:
   Type: AWS::EC2::Subnet
   Properties: 
    AvailabilityZone: ap-northeast-1a
    CidrBlock: 10.1.0.0/24
    VpcId: !Ref VPC 
    Tags: 
     - Key: Name
       Value: !Sub ${NameBase}-public1-ap-northeast-1a

 PublicSubnet2:
   Type: AWS::EC2::Subnet
   Properties: 
    AvailabilityZone: ap-northeast-1c
    CidrBlock: 10.1.10.0/24
    VpcId: !Ref VPC 
    Tags: 
     - Key: Name
       Value: !Sub ${NameBase}-public2-ap-northeast-1c

 PrivateSubnet1:
   Type: AWS::EC2::Subnet
   Properties: 
    AvailabilityZone: ap-northeast-1a
    CidrBlock: 10.1.100.0/24
    VpcId: !Ref VPC 
    Tags: 
     - Key: Name
       Value: !Sub ${NameBase}-private1-ap-northeast-1a

 PrivateSubnet2:
   Type: AWS::EC2::Subnet
   Properties: 
    AvailabilityZone: ap-northeast-1c
    CidrBlock: 10.1.200.0/24
    VpcId: !Ref VPC 
    Tags: 
     - Key: Name
       Value: !Sub ${NameBase}-private2-ap-northeast-1c


 # RouteTable
 # public
 PublicRouteTable: 
   Type: AWS::EC2::RouteTable
   Properties: 
    VpcId: !Ref VPC 
    Tags: 
      - Key: Name
        Value: !Sub ${NameBase}-rtb-public

 # private
 PrivateRouteTable1: 
  Type: AWS::EC2::RouteTable
  Properties: 
    VpcId: !Ref VPC 
    Tags: 
      - Key: Name
        Value: !Sub ${NameBase}-rtb-private1-ap-northeast-1a

 PrivateRouteTable2: 
  Type: AWS::EC2::RouteTable
  Properties: 
    VpcId: !Ref VPC 
    Tags: 
      - Key: Name
        Value: !Sub ${NameBase}-rtb-private2-ap-northeast-1c


 # InternetGateway
 InternetGateway: 
  Type: AWS::EC2::InternetGateway
  Properties:
    Tags:
      - Key: Name
        Value: !Sub ${NameBase}-igw

 # igw Attach
 InternetGatewayAttachment: 
  Type: AWS::EC2::VPCGatewayAttachment
  Properties: 
    InternetGatewayId: !Ref InternetGateway
    VpcId: !Ref VPC


 # Routing
 PublicRoute: 
  Type: AWS::EC2::Route
  Properties: 
    RouteTableId: !Ref PublicRouteTable
    DestinationCidrBlock: 0.0.0.0/0
    GatewayId: !Ref InternetGateway

 
 # RouteTable Associate
 PublicSubnet1RouteTableAssociation: 
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties: 
    SubnetId: !Ref PublicSubnet1 
    RouteTableId: !Ref PublicRouteTable

 PublicSubnet2RouteTableAssociation: 
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties: 
    SubnetId: !Ref PublicSubnet2 
    RouteTableId: !Ref PublicRouteTable

 PrivateSubnet1RouteTableAssociation: 
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties: 
    SubnetId: !Ref PrivateSubnet1 
    RouteTableId: !Ref PrivateRouteTable1

 PrivateSubnet2RouteTableAssociation: 
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties: 
    SubnetId: !Ref PrivateSubnet2
    RouteTableId: !Ref PrivateRouteTable2


Outputs:
 VPCId:
  Description: The ID of the VPC
  Value: !Ref VPC
  Export:
    Name: !Sub ${AWS::StackName}-VPCId

 PublicSubnet1Id:
  Description: The ID of the publicsubnet1
  Value: !Ref PublicSubnet1
  Export:
    Name: !Sub ${AWS::StackName}-PublicSubnet1Id

 PublicSubnet2Id:
  Description: The ID of the publicsubnet2
  Value: !Ref PublicSubnet2
  Export:
    Name: !Sub ${AWS::StackName}-PublicSubnet2Id

 PrivateSubnet1Id:
  Description: The ID of the PrivateSubnet1
  Value: !Ref PrivateSubnet1
  Export:
    Name: !Sub ${AWS::StackName}-PrivateSubnet1Id

 PrivateSubnet2Id:
  Description: The ID of the PrivateSubnet2
  Value: !Ref PrivateSubnet2
  Export:
    Name: !Sub ${AWS::StackName}-PrivateSubnet2Id
